---
- name: Configure mailserver.env
  ansible.builtin.lineinfile:
    path: "{{ dms_install_dir }}/mailserver.env"
    regexp: "^{{ item.key }}=.*"
    line: "{{ item.key }}={{ item.value }}"
  loop: "{{ dms_env_vars | dict2items }}"

- name: Generate compose.override.yaml
  ansible.builtin.template:
    src: compose.override.j2
    dest: "{{ dms_install_dir }}/compose.override.yaml"
    lstrip_blocks: yes
    mode: "0644"

- name: Start up containers
  community.docker.docker_compose_v2:
    project_src: "{{ dms_install_dir }}"
    state: present
  register: compose_output

- name: Setup email accounts
  ansible.builtin.include_tasks: setup-account.yml
  loop: "{{ dms_accounts }}"
  no_log: true

- name: Generate DKIM keys
  community.docker.docker_container_exec:
    container: mailserver
    command: /bin/bash -c "setup config dkim keysize {{ dms_dkim_keysize }}"

- name: Change compose state
  community.docker.docker_compose_v2:
    project_src: "{{ dms_install_dir }}"
    state: "{{ dms_compose_state }}"
