---
- name: Configure mailserver.env
  ansible.builtin.lineinfile:
    path: "{{ dms_install_dir }}/mailserver.env"
    regexp: "^{{ item.key }}=.*"
    line: "{{ item.key }}={{ item.value }}"
  loop: "{{ dms_env_vars | dict2items }}"

- name: Configure hostname
  ansible.builtin.lineinfile:
    path: "{{ dms_install_dir }}/compose.yaml"
    regexp: '^(\s*)hostname:.*'
    line: '\1hostname: {{ dms_hostname }}'
    state: present
    backrefs: true

- name: Add NET_ADMIN capability for fail2ban
  ansible.builtin.replace:
    path: "{{ dms_install_dir }}/compose.yaml"
    regexp: '(\s+)# cap_add:\n(\s+)#   - NET_ADMIN'
    replace: '\1cap_add:\n\2  - NET_ADMIN'
  when: "'ENABLE_FAIL2BAN' in dms_env_vars and dms_env_vars['ENABLE_FAIL2BAN'] == 1"

- name: Start up containers
  community.docker.docker_compose_v2:
    project_src: "{{ dms_install_dir }}"
    state: present
  register: compose_output

- name: Register existance of email accounts
  ansible.builtin.lineinfile:
    path: "{{ dms_install_dir }}/docker-data/dms/config/postfix-accounts.cf"
    search_string: '{{ item.email }}'
    line: '{{ item.email }}'
    state: present
  check_mode: true
  no_log: true
  register: emails_exist
  loop: "{{ dms_accounts }}"
  when: dms_accounts | length > 0

- name: Add new email accounts
  community.docker.docker_container_exec:
    container: mailserver
    command: /bin/bash -c "setup email add {{ item.email }} '{{ item.password }}'"
  no_log: true
  loop: "{{ dms_accounts }}"
  loop_control:
    index_var: index
  when: emails_exist.results[index].msg == "line added"

- name: Update existing email accounts
  community.docker.docker_container_exec:
    container: mailserver
    command: /bin/bash -c "setup email update {{ item.email }} '{{ item.password }}'"
  no_log: true
  loop: "{{ dms_accounts }}"
  loop_control:
    index_var: index
  when: emails_exist.results[index].msg == "line replaced"

- name: Generate DKIM keys
  community.docker.docker_container_exec:
    container: mailserver
    command: /bin/bash -c "setup config dkim keysize {{ dms_dkim_keysize }}"

- name: Shut down containers
  community.docker.docker_compose_v2:
    project_src: "{{ dms_install_dir }}"
    state: absent
