---
- name: Setup basic files & directory structure
  ansible.builtin.import_tasks: install.yml

- name: Setup SSL provider
  ansible.builtin.import_tasks: setup-ssl.yml
  when: dms_ssl_provider

- name: Setup configuration & containers
  ansible.builtin.import_tasks: configure.yml
