---
- name: Configure hostname in compose.yaml
  ansible.builtin.lineinfile:
    path: "{{ dms_install_dir }}/compose.yaml"
    regexp: '^(\s*)hostname:.*'
    line: '\1hostname: {{ dms_hostname }}'
    state: present
    backrefs: true

- name: Add NET_ADMIN capability for fail2ban
  ansible.builtin.replace:
    path: "{{ dms_install_dir }}/compose.yaml"
    regexp: '(\s+)# cap_add:\n(\s+)#   - NET_ADMIN'
    replace: '\1cap_add:\n\2  - NET_ADMIN'
  when: "'ENABLE_FAIL2BAN' in dms_env_vars and dms_env_vars['ENABLE_FAIL2BAN'] == 1"

- name: Add certificate volume
  ansible.builtin.lineinfile:
    insertafter: ".*volumes:$"
    path: "{{ dms_install_dir }}/compose.yaml"
    line: "      - {{ dms_ssl_cert_path }}:/etc/letsencrypt/acme.json:ro"
    state: present
  when: dms_ssl_provider == 'traefik'

- name: Add traefik & whoami service
  ansible.builtin.blockinfile:
    path: "{{ dms_install_dir }}/compose.yaml"
    marker: ""
    block: "{{ lookup('ansible.builtin.template', './traefik.j2') }}"
  when: dms_ssl_provider == 'traefik'
