---
- name: Configure mailserver.env
  ansible.builtin.lineinfile:
    path: "{{ dms_install_dir }}/mailserver.env"
    regexp: "^{{ item.key }}=.*"
    line: "{{ item.key }}={{ item.value }}"
  loop: "{{ dms_env_vars | dict2items }}"

- name: Configure hostname in compose.yaml
  ansible.builtin.lineinfile:
    path: "{{ dms_install_dir }}/compose.yaml"
    regexp: '^(\s*)hostname:.*'
    line: '\1hostname: {{ dms_hostname }}'
    state: present
    backrefs: true

- name: Add NET_ADMIN capability for fail2ban
  ansible.builtin.replace:
    path: "{{ dms_install_dir }}/compose.yaml"
    regexp: '(\s+)# cap_add:\n(\s+)#   - NET_ADMIN'
    replace: '\1cap_add:\n\2  - NET_ADMIN'
  when: "'ENABLE_FAIL2BAN' in dms_env_vars and dms_env_vars['ENABLE_FAIL2BAN'] == 1"
