---
- name: Register existance of email account
  ansible.builtin.lineinfile:
    path: "{{ dms_install_dir }}/docker-data/dms/config/postfix-accounts.cf"
    search_string: '{{ item.email }}'
    line: '{{ item.email }}'
    state: present
  check_mode: true
  register: account_exists

- name: Add new email account
  community.docker.docker_container_exec:
    container: mailserver
    command: /bin/bash -c "setup email add {{ item.email }} '{{ item.password }}'"
  when: account_exists.msg == "line added"

- name: Update existing email account
  community.docker.docker_container_exec:
    container: mailserver
    command: /bin/bash -c "setup email update {{ item.email }} '{{ item.password }}'"
  when: account_exists.msg == "line replaced"
