---
- name: Setup install dir
  ansible.builtin.file:
    path: "{{ dms_install_dir }}"
    state: directory
    mode: "0755"

- name: Download compose & env file
  ansible.builtin.get_url:
    url: "{{ dms_repo_url }}/{{ item }}"
    dest: "{{ dms_install_dir }}"
    mode: "0644"
  loop:
    - compose.yaml
    - mailserver.env

- name: Setup volume directories
  ansible.builtin.file:
    path: "{{ dms_install_dir }}/docker-data/dms/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - mail-data
    - mail-state
    - mail-logs
    - config

- name: Setup mail accounts config
  ansible.builtin.file:
    path: "{{ dms_install_dir }}/docker-data/dms/config/postfix-accounts.cf"
    state: touch
    mode: "0644"

- name: Configure mailserver.env
  ansible.builtin.lineinfile:
    path: "{{ dms_install_dir }}/mailserver.env"
    regexp: "^{{ item.key }}=.*"
    line: "{{ item.key }}={{ item.value }}"
  loop: "{{ dms_env_vars | dict2items }}"
