---
- name: Validate SSL provider choice
  ansible.builtin.fail:
    msg: "Value of dms_ssl_provider must be one of: {{ dms_ssl_defaults.keys() | join(', ') }} got {{ dms_ssl_provider }}"
  when: dms_ssl_provider not in dms_ssl_defaults.keys()

- name: Validate SSL provider requires email
  ansible.builtin.fail:
    msg: "Value of dms_ssl_email must be set in order to use SSL provider: {{ dms_ssl_provider }}"
  when: not dms_ssl_email and dms_ssl_defaults[dms_ssl_provider].requires_email

- name: Set SSL path to default
  ansible.builtin.set_fact:
    dms_ssl_path: "{{ dms_ssl_defaults[dms_ssl_provider].source_path }}"
  when: not dms_ssl_path

- name: Add certificate volume
  ansible.builtin.lineinfile:
    insertafter: ".*volumes:$"
    path: "{{ dms_install_dir }}/compose.yaml"
    line: "      - {{ dms_ssl_path }}:{{ dms_ssl_defaults[dms_ssl_provider].target_path }}"
    state: present

- name: Add SSL provider block
  ansible.builtin.blockinfile:
    path: "{{ dms_install_dir }}/compose.yaml"
    marker: ""
    block: "{{ lookup('ansible.builtin.template', './providers/' + dms_ssl_provider + '.j2') }}"
