---
- name: Add new email account
  community.docker.docker_container_exec:
    container: mailserver
    command: /bin/bash -c "setup email add {{ item.email }} '{{ item.password }}'"

- name: Add aliases for email account
  community.docker.docker_container_exec:
    container: mailserver
    command: /bin/bash -c "setup alias add {{ alias }} {{ item.email }}"
  loop: "{{ item.aliases }}"
  loop_control:
    loop_var: alias
